"""Regelbasierte Angebotserkennung (Kopfdaten, Tabellen, Freitext, Lernen)."""

from __future__ import annotations

from .email_merge import (
    MAIL_SOURCE_MARK,
    UNMATCHED_ISSUE_CODE,
    apply_email_header,
    apply_email_supplements,
    is_statement,
    mail_segments,
    report_unmatched,
)
from .confidence import (
    BASE_CONFIDENCE,
    PATH_FREETEXT,
    PATH_MANUAL,
    PATH_TABLE_HEADER,
    PATH_TABLE_NO_HEADER,
    apply_confidence,
    compute_confidence,
)
from .freetext_extractor import FreetextExtractor, FreetextResult
from .header_rules import (
    HEADER_RULES,
    HeaderMatch,
    HeaderRule,
    apply_header_matches,
    extract_header_fields,
    find_incoterm,
    label_value_pairs,
    label_value_text,
)
from .material_roles import (
    CUSTOMER_MARKERS,
    SUPPLIER_MARKERS,
    compile_own_pattern,
    find_labelled_material_matches,
    find_labelled_material_numbers,
    header_role,
    matches_own_pattern,
    own_ratio,
    resolve_position_roles,
)
from .learning import LearningConfig, LearningReport, describe_learning, forget_rule, \
    learn_from_corrections, suggest_exclude_keyword
from .plausibility import (
    CODE_DOCUMENT_TOTAL_MISMATCH,
    CODE_LINE_TOTAL_MISMATCH,
    CODE_POSITION_GAP,
    CODE_PRICE_OUTLIER,
    check_document_total,
    check_line_totals,
    check_position_numbers,
    check_price_outliers,
    expected_line_total,
    find_document_total,
    position_value,
    run_checks,
)
from .price_parsing import (
    PriceInfo,
    is_carryover_row,
    is_page_noise_row,
    parse_price_text,
)
from .profiles import (
    InMemoryProfileStore,
    JsonProfileStore,
    VendorProfile,
    VendorProfileStore,
    apply_profile,
    fingerprint,
    match_profile,
    new_profile,
)
from .table_extractor import (
    ColumnAssignment,
    ExtractionResult,
    TableAnalysis,
    TableExtractor,
    detect_day_first,
    find_price_tiers,
    is_summary_row,
    parse_date_ordered,
    parse_number,
)

__all__ = [
    "BASE_CONFIDENCE",
    "CODE_DOCUMENT_TOTAL_MISMATCH",
    "CODE_LINE_TOTAL_MISMATCH",
    "CODE_POSITION_GAP",
    "CODE_PRICE_OUTLIER",
    "PATH_FREETEXT",
    "PATH_MANUAL",
    "PATH_TABLE_HEADER",
    "PATH_TABLE_NO_HEADER",
    "PriceInfo",
    "apply_confidence",
    "check_document_total",
    "check_line_totals",
    "check_position_numbers",
    "check_price_outliers",
    "compute_confidence",
    "expected_line_total",
    "find_document_total",
    "is_carryover_row",
    "is_page_noise_row",
    "parse_price_text",
    "position_value",
    "run_checks",
    "MAIL_SOURCE_MARK",
    "UNMATCHED_ISSUE_CODE",
    "apply_email_header",
    "apply_email_supplements",
    "is_statement",
    "mail_segments",
    "report_unmatched",
    "CUSTOMER_MARKERS",
    "SUPPLIER_MARKERS",
    "compile_own_pattern",
    "find_labelled_material_matches",
    "find_labelled_material_numbers",
    "header_role",
    "label_value_pairs",
    "label_value_text",
    "matches_own_pattern",
    "own_ratio",
    "resolve_position_roles",
    "ColumnAssignment",
    "ExtractionResult",
    "FreetextExtractor",
    "FreetextResult",
    "HEADER_RULES",
    "HeaderMatch",
    "HeaderRule",
    "InMemoryProfileStore",
    "JsonProfileStore",
    "LearningConfig",
    "LearningReport",
    "TableAnalysis",
    "TableExtractor",
    "VendorProfile",
    "VendorProfileStore",
    "apply_header_matches",
    "apply_profile",
    "describe_learning",
    "detect_day_first",
    "parse_date_ordered",
    "extract_header_fields",
    "find_incoterm",
    "find_price_tiers",
    "fingerprint",
    "forget_rule",
    "is_summary_row",
    "learn_from_corrections",
    "match_profile",
    "new_profile",
    "parse_number",
    "suggest_exclude_keyword",
]
